# Generated by Django 3.0.1 on 2020-03-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='scraper.NewsWebsite'),
        ),
    ]
