# Generated by Django 3.0.1 on 2020-03-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200314_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswebsite',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
